before_script:
  - export FRAMAC_SHARE=$(frama-c-config -print-share-path)
  - coqc -R $FRAMAC_SHARE/wp/coqwp "" verif/Lemmas.v

job:
  tags:
    - framac
  script:
    - extricate --type contiki --config verif/contiki_extricate.conf --done verif/contiki_status.conf --kernel . --module os/lib/
    - compare_verdicts verif/verdicts.txt verif/new_verdicts.txt
  artifacts:
    paths:
      - verif/new_verdicts.txt
      - wp-out
      - result
    expire_in: 1 week

